services:

  # MySQL database service
  mysql:
    image: mysql
    container_name: mysql-container # Lowercase and underscores (naming convention)
    restart: always
    ports:
      - "3306:3306" # Expose MySQL port to host    
    environment: 
      MYSQL_ROOT_PASSWORD: root # Set a strong password for the MySQL root user
    volumes:
      - ./data:/var/lib/mysql # Persist data volume for database     
    networks:
      - mysql-pma-network
      
      
  # phpMyAdmin service (management UI)
  phpmyadmin:
    image: phpmyadmin 
    container_name: pma-container
    restart: always
    ports:
      - "8081:80" # Maps port 8081 on your host to port 80 (default for phpMyAdmin) inside the container
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql # This ensures the database service is started before phpMyAdmin attempts to connect
    networks:
      - mysql-pma-network
      
networks:
  mysql-pma-network: 